// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yoishkelodqyzpqevqnk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvaXNoa2Vsb2RxeXpwcWV2cW5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMTEyMDEsImV4cCI6MjA2MzU4NzIwMX0.3v9J1RHxBnKV__zf4HbAR3R30zhBJKfev3a_N_G354o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);